import {
  VisualElement,
  Visualizer,
  AudioData,
  VisualizerParams,
} from "../shared/types/visualizer.types";

export const defaultCustomizations = {
  background: {
    backgroundType: "color",
    color: "#0a0a0a",
    gradient: false,
    gradientStart: "#000000",
    gradientEnd: "#ffffff",
    image: null,
    imageFile: null,
    imageScale: 1,
    imageOffsetX: 0,
    imageOffsetY: 0,
  },
  particle: {
    color: "#00ff88",
    size: 0.1,
    opacity: 0.8,
    speed: 1.0,
    intensity: 1,
    count: 3000,
    responseTo: "bass" as const,
  },
  grid: {
    color: "#00ff88",
    opacity: 0.6,
    intensity: 1,
    size: 20,
    divisions: 30,
    responseTo: "mid" as const,
  },
  shape: {
    color: "#ff0088",
    opacity: 0.8,
    intensity: 1,
    geometry: "cube" as const,
    size: 1,
    rotationSpeed: 1,
    responseTo: "treble" as const,
  },
  wave: {
    color: "#0088ff",
    opacity: 0.7,
    intensity: 1,
    amplitude: 2,
    frequency: 1,
    speed: 1,
    points: 50,
    responseTo: "overall" as const,
  },
};

export const defaultVisualElements: VisualElement[] = [
  {
    id: "background",
    type: "background",
    name: "Background",
    visible: true,
    position: [0, 2, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    customization: defaultCustomizations.background,
  },
  {
    id: "main-particles",
    type: "particle",
    name: "Main Particles",
    visible: true,
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    customization: defaultCustomizations.particle,
  },
  {
    id: "grid-lines",
    type: "grid",
    name: "Grid Lines",
    visible: true,
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    customization: defaultCustomizations.grid,
  },
];

export const defaultVisualizers: Visualizer[] = [
  {
    id: "3",
    name: "Wave Ripple",
    type: "waveform",
    thumbnail: "🌊",
    visualizerType: "waveform3D",
  },
  {
    id: "4",
    name: "Spiral Galaxy",
    type: "3d",
    thumbnail: "🌌",
    visualizerType: "morphing",
  },
  {
    id: "61",
    name: "Galaxy Nebula",
    type: "cosmic",
    thumbnail: "🌠",
    visualizerType: "galaxyNebula",
  },
  {
    id: "62",
    name: "Audio Tunnel",
    type: "3d",
    thumbnail: "🎧",
    visualizerType: "audioTunnel",
  },
  {
    id: "63",
    name: "Audio Mesh",
    type: "wireframe",
    thumbnail: "🔲",
    visualizerType: "audioMesh",
  },
  {
    id: "64",
    name: "Kaleidoscope 2.0",
    type: "geometric",
    thumbnail: "🎨",
    visualizerType: "kaleidoscope2",
  },
  {
    id: "5",
    name: "Neon Grid",
    type: "cyber",
    thumbnail: "⚡",
    visualizerType: "cyberGrid",
  },
  {
    id: "6",
    name: "Audio Sphere",
    type: "3d",
    thumbnail: "🔮",
    visualizerType: "biomorphic",
  },
  {
    id: "7",
    name: "Liquid Motion",
    type: "liquid",
    thumbnail: "💧",
    visualizerType: "liquid",
  },
  {
    id: "8",
    name: "Geometric Patterns",
    type: "geometric",
    thumbnail: "🔷",
    visualizerType: "geometric",
  },
  {
    id: "9",
    name: "Spectrum Analyzer",
    type: "bars",
    thumbnail: "📊",
    visualizerType: "spectrum",
  },
  {
    id: "10",
    name: "DNA Double Helix",
    type: "biological",
    thumbnail: "🧬",
    visualizerType: "dnaHelix",
  },
  {
    id: "11",
    name: "Crystal Lattice",
    type: "geometric",
    thumbnail: "💎",
    visualizerType: "crystalLattice",
  },
  {
    id: "12",
    name: "Plasma Energy",
    type: "particles",
    thumbnail: "⚡",
    visualizerType: "plasmaField",
  },
  {
    id: "13",
    name: "Fractal Tree",
    type: "fractal",
    thumbnail: "🌳",
    visualizerType: "fractalTree",
  },
  {
    id: "14",
    name: "Kaleidoscope",
    type: "geometric",
    thumbnail: "🔆",
    visualizerType: "kaleidoscope",
  },
  {
    id: "16",
    name: "Quantum Field",
    type: "quantum",
    thumbnail: "⚛️",
    visualizerType: "quantumField",
  },
  {
    id: "17",
    name: "Solar Flare",
    type: "cosmic",
    thumbnail: "☀️",
    visualizerType: "solarFlare",
  },
  {
    id: "18",
    name: "Aurora Borealis",
    type: "wave",
    thumbnail: "🌈",
    visualizerType: "auroraWaves",
  },
  {
    id: "24",
    name: "Voronoi Cells",
    type: "geometric",
    thumbnail: "🔶",
    visualizerType: "voronoiCells",
  },

  {
    id: "27",
    name: "Crystal Cave",
    type: "geometric",
    thumbnail: "💠",
    visualizerType: "crystalCave",
  },

  {
    id: "34",
    name: "Supernova",
    type: "cosmic",
    thumbnail: "💥",
    visualizerType: "supernova",
  },

  {
    id: "40",
    name: "Crystal Matrix",
    type: "geometric",
    thumbnail: "💠",
    visualizerType: "crystalMatrix",
  },
  {
    id: "41",
    name: "Liquid Mercury",
    type: "liquid",
    thumbnail: "🌊",
    visualizerType: "liquidMercury",
  },
  {
    id: "42",
    name: "Cyber Grid 2.0",
    type: "cyber",
    thumbnail: "🔷",
    visualizerType: "cyberGrid2",
  },
  {
    id: "43",
    name: "Plasma Storm",
    type: "energy",
    thumbnail: "🌪️",
    visualizerType: "plasmaStorm",
  },
  {
    id: "44",
    name: "Holographic Grid",
    type: "cyber",
    thumbnail: "👁️",
    visualizerType: "holographicGrid",
  },
  {
    id: "45",
    name: "Morphing Crystals",
    type: "geometric",
    thumbnail: "🔮",
    visualizerType: "morphingCrystals",
  },

  {
    id: "47",
    name: "Fractal Expansion",
    type: "fractal",
    thumbnail: "🌀",
    visualizerType: "fractalExpansion",
  },
  {
    id: "48",
    name: "Celestial Symphony",
    type: "cosmic",
    thumbnail: "🎼",
    visualizerType: "celestialSymphony",
  },
  {
    id: "49",
    name: "Neural Fireworks",
    type: "network",
    thumbnail: "🎆",
    visualizerType: "neuralFireworks",
  },
  {
    id: "50",
    name: "Quantum Flux",
    type: "quantum",
    thumbnail: "⚡",
    visualizerType: "quantumFlux",
  },
  {
    id: "51",
    name: "Crystal Resonance",
    type: "geometric",
    thumbnail: "💎",
    visualizerType: "crystalResonance",
  },
  {
    id: "52",
    name: "Time Vortex",
    type: "cosmic",
    thumbnail: "⏳",
    visualizerType: "timeVortex",
  },

  {
    id: "56",
    name: "Particle Sphere",
    type: "particles",
    thumbnail: "🌐",
    visualizerType: "particleSphere",
  },
  {
    id: "57",
    name: "Cube Grid",
    type: "grid",
    thumbnail: "🧊",
    visualizerType: "cubeGrid",
  },
  {
    id: "58",
    name: "Spiral Helix",
    type: "3d",
    thumbnail: "🌀",
    visualizerType: "spiralHelix",
  },
  {
    id: "59",
    name: "Pulsing Rings",
    type: "wave",
    thumbnail: "💫",
    visualizerType: "pulsingRings",
  },
  {
    id: "60",
    name: "Crystal Formation",
    type: "geometric",
    thumbnail: "❄️",
    visualizerType: "crystalFormation",
  },
];

export const defaultAudioData: AudioData = {
  frequencyData: new Uint8Array(1024),
  timeData: new Float32Array(2048),
  beatInfo: {
    isBeat: false,
    strength: 0,
    bandStrengths: { bass: 0, mid: 0, treble: 0 },
  },
  audioLevel: 0,
};

export const defaultParams: VisualizerParams = {
  visualizerType: "audioReactive",
  colorScheme: "cyberpunk",
  intensity: 4,
  speed: 20,
  rotationSpeed: 0,
  particleCount: 6000,
  bloom: true,
  wireframe: false,
  mirrorEffect: true,
  complexity: 10,
  scale: 1.3,
  bassBoost: true,
  reverb: false,
  frequencyRange: [18, 20000],
  smoothing: 1,
  beatDetection: true,
  patternDensity: 18,
  objectSize: 2.4,
  morphSpeed: 110,
  fluidity: 80,
  glowIntensity: 80,
  reactionSpeed: 85,
};
