import { Zap, Sparkles, Volume2, Palette, Box, Camera } from "lucide-react";

export const categories = [
  { id: "basic", label: "Basic", icon: Zap, color: "text-yellow-400" },
  { id: "camera", label: "Camera", icon: Camera, color: "text-blue-400" },
  {
    id: "animation",
    label: "Animation",
    icon: Sparkles,
    color: "text-purple-400",
  },
  { id: "visual", label: "Visual", icon: Palette, color: "text-cyan-400" },
  { id: "audio", label: "Audio", icon: Volume2, color: "text-emerald-400" },
  { id: "effects", label: "Effects", icon: Box, color: "text-pink-400" },
];

export const defaultCameraParams = {
  cameraDistance: 15,
  cameraHeight: 8,
  cameraAngle: 45,
  cameraAutoRotate: true,
  cameraRotationSpeed: 0.5,
  cameraFOV: 75,
  cameraZoom: 1,
  cameraFollowBeat: false,
};

export const sliderConfigs = {
  speed: {
    min: 0.1,
    max: 5,
    step: 0.1,
    label: "Speed",
    category: "basic",
    icon: "⚡",
  },
  intensity: {
    min: 0,
    max: 100,
    step: 1,
    label: "Intensity",
    category: "basic",
    icon: "📊",
  },
  scale: {
    min: 0.1,
    max: 5,
    step: 0.1,
    label: "Scale",
    category: "basic",
    icon: "📐",
  },

  cameraDistance: {
    min: 5,
    max: 50,
    step: 1,
    label: "Distance",
    category: "camera",
    icon: "📏",
  },
  cameraHeight: {
    min: 0,
    max: 20,
    step: 0.5,
    label: "Height",
    category: "camera",
    icon: "⬆️",
  },
  cameraAngle: {
    min: 0,
    max: 360,
    step: 1,
    label: "Angle",
    category: "camera",
    icon: "📐",
  },
  cameraRotationSpeed: {
    min: 0,
    max: 2,
    step: 0.1,
    label: "Rotation Speed",
    category: "camera",
    icon: "🌀",
  },
  cameraFOV: {
    min: 30,
    max: 120,
    step: 1,
    label: "Field of View",
    category: "camera",
    icon: "👁️",
  },
  cameraZoom: {
    min: 0.5,
    max: 3,
    step: 0.1,
    label: "Zoom",
    category: "camera",
    icon: "🔍",
  },

  rotationSpeed: {
    min: 0,
    max: 100,
    step: 1,
    label: "Rotation Speed",
    category: "animation",
    icon: "🌀",
  },
  morphSpeed: {
    min: 0,
    max: 200,
    step: 1,
    label: "Morph Speed",
    category: "animation",
    icon: "🔄",
  },
  fluidity: {
    min: 0,
    max: 100,
    step: 1,
    label: "Fluidity",
    category: "animation",
    icon: "💧",
  },
  reactionSpeed: {
    min: 0,
    max: 100,
    step: 1,
    label: "Reaction Speed",
    category: "animation",
    icon: "⚡",
  },

  objectSize: {
    min: 0.1,
    max: 10,
    step: 0.1,
    label: "Object Size",
    category: "visual",
    icon: "🔲",
  },
  glowIntensity: {
    min: 0,
    max: 100,
    step: 1,
    label: "Glow Intensity",
    category: "visual",
    icon: "✨",
  },
  complexity: {
    min: 1,
    max: 50,
    step: 1,
    label: "Complexity",
    category: "visual",
    icon: "🎨",
  },
  patternDensity: {
    min: 1,
    max: 50,
    step: 1,
    label: "Pattern Density",
    category: "visual",
    icon: "🔷",
  },

  smoothing: {
    min: 0.1,
    max: 5,
    step: 0.1,
    label: "Smoothing",
    category: "audio",
    icon: "🎵",
  },
  particleCount: {
    min: 100,
    max: 20000,
    step: 100,
    label: "Particle Count",
    category: "audio",
    icon: "✨",
  },

  bloom: {
    isToggle: true,
    label: "Bloom Effect",
    category: "effects",
    icon: "🌟",
  },
  wireframe: {
    isToggle: true,
    label: "Wireframe",
    category: "effects",
    icon: "🔲",
  },
  mirrorEffect: {
    isToggle: true,
    label: "Mirror Effect",
    category: "effects",
    icon: "🪞",
  },
  bassBoost: {
    isToggle: true,
    label: "Bass Boost",
    category: "effects",
    icon: "🔊",
  },
  reverb: { isToggle: true, label: "Reverb", category: "effects", icon: "🎚️" },
  beatDetection: {
    isToggle: true,
    label: "Beat Detection",
    category: "effects",
    icon: "🥁",
  },
  cameraAutoRotate: {
    isToggle: true,
    label: "Auto Rotate",
    category: "camera",
    icon: "🔄",
  },
  cameraFollowBeat: {
    isToggle: true,
    label: "Follow Beat",
    category: "camera",
    icon: "🥁",
  },
};

export const presets = {
  default: {
    cameraDistance: 15,
    cameraHeight: 8,
    cameraAngle: 45,
    cameraFOV: 75,
  },
  "close-up": {
    cameraDistance: 8,
    cameraHeight: 4,
    cameraAngle: 30,
    cameraFOV: 60,
  },
  "wide-angle": {
    cameraDistance: 25,
    cameraHeight: 12,
    cameraAngle: 60,
    cameraFOV: 90,
  },
  "top-down": {
    cameraDistance: 20,
    cameraHeight: 20,
    cameraAngle: 0,
    cameraFOV: 65,
  },
  "low-angle": {
    cameraDistance: 12,
    cameraHeight: 2,
    cameraAngle: 15,
    cameraFOV: 80,
  },
  orbiting: {
    cameraAutoRotate: true,
    cameraRotationSpeed: 1,
    cameraDistance: 18,
    cameraHeight: 10,
  },
};

export const defaultParams = {
  speed: 0.5,
  intensity: 90,
  rotationSpeed: 20,
  particleCount: 6000,
  scale: 1.3,
  objectSize: 2.4,
  morphSpeed: 110,
  fluidity: 80,
  glowIntensity: 80,
  reactionSpeed: 85,
  complexity: 10,
  patternDensity: 18,
  smoothing: 1,
  bassBoost: true,
  bloom: true,
  wireframe: false,
  mirrorEffect: true,
  reverb: false,
  beatDetection: true,
  cameraDistance: 15,
  cameraHeight: 8,
  cameraAngle: 45,
  cameraAutoRotate: true,
  cameraRotationSpeed: 0.5,
  cameraFOV: 75,
  cameraZoom: 1,
  cameraFollowBeat: false,
};
